@extends('frontend.listing.layout.app')
@empty($category)
@section('title','Privacy Policy')    
@endempty
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
@section('content')
<section class="inner_page_breadcrumb style3" style="background-image:url('https://designwebo.com/wp-content/uploads/2018/04/privacy-policy-banner.jpg')">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8">
                <div class="blog_single_post_heading text-center">
                    <div class="contents">
                        <h2 class="text-white mb15">Privacy Policy</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Single Post -->
<section class="blog_post_container pb70">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-9">
                <div class="main_blog_post_content">
                    <div class="mbp_thumb_post">
                       <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:27px;line-height:115%;">Privacy Policy</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>We are a real estate information service connecting people in the real estate market. &nbsp;MAKAI ROOMS and our subsidiaries and affiliates provide you with access to a variety of services, including but not limited to the www.makairooms.com website (the &quot;Website&quot;) and all the products and services available through our website (collectively the &quot;Services&quot;). This Website is owned and operated by (&hellip;&hellip;&hellip;&hellip;&hellip;..). Having its registered office at Plot No.7, Behind Lal Diggi, Ward No. 28, Near Jai Paltan Gate, Alwar, Rajasthan 301001.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Our Privacy Policy is incorporated as part of the makairooms.com Terms of Use. Please read this Privacy Policy and our Terms of Use carefully before using our Services. By using makairooms.com&rsquo;s Services, you agree to the provisions of this Privacy Policy. If you do not want to be bound by our Privacy Policy, please do not use our Services.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u><span style="font-size:19px;line-height:115%;">Why We Collect Information from You</span></u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>MAKAI ROOMS is a real estate information service. To provide our Services, we use the information we collect to:</p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Help you find the most relevant information for your situation by customizing our Services to optimize your experience;</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Keep you connected with MAKAI ROOMS across the internet and update you with residential real estate-related news and information; and</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Put you in touch with the right people to rent, or research residential real estate, obtain a mortgage and to optimize the information we share with those parties to initiate a productive and efficient relationship.</strong></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Our goal in this policy is to be completely transparent about the data we collect, why we collect it, and how we use it, in order to make finding your new home a pleasant and fun experience.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u><span style="font-size:19px;line-height:115%;">Policy Application</span></u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Some parts of this Policy are directed at specific types of people and we use specific terminology to refer to them, which we define below. This Policy applies to everyone who uses our Services, but sometimes we direct parts of it toward particular groups of users.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Users:</u></strong> &quot;Users&quot; are everyone who uses our Services.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Real Estate Service Providers (RESPs)</u></strong><u>:</u> &quot;Real Estate Professionals,&quot; or &quot;RESPs&quot; are users who have created accounts (free or paid) with us to sell or rent real estate, participate in our advertising services, and participate in other Services that we direct toward the professional real estate community. RESPs include landlords, agents, developers, institutional property consultants, mortgage professionals PG/Private Hostel, Religious Institution/ Dorm and Educational Institution / Hostel and subscribers. We send leads to RESPs on your behalf, as described in this Policy.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Other Service Providers (OSPs):</u></strong> Are those professionals or user who register or create account (free or paid) with us to sell or rent other supporting services and products using MAKAI ROOMS services or platforms.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u><span style="font-size:19px;line-height:115%;">What Information Do We Collect, and Where Do We Get It</span></u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>We Collect Some Information From All Visitors to Our Website: Like many online services, we use technologies like session and persistent cookies, web beacons (tiny image files on web pages that communicate information about the page viewer to the beacon owner), log data, and third-party analytics services to collect and analyse information about all users of our Services This includes things like User search preferences, interaction with ads on our Website, and location.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Our servers automatically record information (&quot;Log Data&quot;) created by your use of the Services. Log Data may include information such as your IP address, browser type, operating system, the referring web page, pages visited, location, your mobile carrier, device, search terms, and cookie information. We receive Log Data when you interact with our Services, for example, when you visit our websites, sign into our Services, or interact with our email notifications. We use Log Data to provide our Services and to measure, customize, and improve them, as well as collect and use them in the aggregate. This Policy does not apply to, nor do we take any responsibility for any information that is collected by any third party either using the Website or through any links on the Website or through any of the advertisements.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Cookies are small data files that we transfer to your computer. We use &quot;session&quot; cookies to keep you logged in while you use our Services, to better understand how you interact with our Services, and to monitor aggregate usage and web traffic information on our Services. We use &quot;persistent&quot; cookies to recognize you each time you return to our Services. For example, we create a persistent cookie that includes some basic information about you, like your most recent search and whether an agent responded to a query you sent using Makairooms.com&apos;s Services. We use this persistent cookie to remember your preferences and, if you create an account, to make your user experience consistent after you register.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Most internet browsers automatically accept cookies, but you can change your settings or use third-party tools to refuse cookies or prompt you before accepting cookies from the websites you visit. You can also use your browser settings or other tools to delete cookies you already have. Please be aware that some parts of our Services may not work for you if you disable cookies.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Information We Collect from RESPs and OSP: If you create a RESP and OSP account with us, whether as a landlord, agent, subscriber or any other service provider we will ask you to provide certain information in order to set up your account. We ask all RESPs and OSP to provide a name, a company (if available), a phone number, and an email address. If you create a paid RESP and OSP account and become a subscriber, we require you to submit all of the information required from landlords and agents as well as a description of your campaign. If you are a subscriber, a Makairooms.com representative may call you to verify your information.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Additional Information About You that We Obtain from Third Parties:</u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;We may sometimes obtain information about you from third parties and use it to help agents serve you better. For example, our partners may help us provide predictions of your income range and how likely you may be to purchase a home. We will share this augmented data only with selected RESPs (subscribers) and OSP who you choose to share information with by contacting them through the MAKAI ROOMS Services.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Location Data:</u></strong> If you provide location information (like a postcode code, street address, Locality, District or even just a city) during the registration process or at any other time via your account settings, we will store that information and associate it with your account.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>We may use and store information about your location to provide localized features, to analyse our Services with the help of third-party analytics services, to provide you with relevant advertising and marketing materials, and otherwise to improve and customize our Services.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u><span style="font-size:19px;line-height:115%;">How We Share Your Information</span></u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>As you use, access and navigate our Website, we collect various information, which may either be personally identifiable information or information that is not personally identifiable. This information is classified as:</p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>&ldquo;Personal Information&rdquo; which means personally identifiable information for example your name, address, age, email address and phone number.</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>&ldquo;Sensitive Personal Information&rdquo; which means your financial information, your passwords, any biometric, medical or health related information.</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>&ldquo;Other Information&rdquo; which means all other information other than &ldquo;Personal Information&rdquo; or &ldquo;Sensitive Personal Information.&rdquo; For example, the nature of device information, your usage patterns, preferences, logs which are created when you access and use the Website, local caches on your browser, your location, IP address and the like. Please note that this is not an exhaustive list and serves as examples only.</strong></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Any personal information will be used to allow you to login to your account or to resolve specific service issues, inform you of our new services or features and to communicate with you in relation to your use of the Website. Any other information we collect will be used for:</p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>our business purposes and this may include the viewing or advertising rental properties or to use associated services;</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>analytical purposes, data usage;</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>improving the Website, or your user experience; and</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Providing targeted advertisements to you.</strong></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Sharing the information with our partners for business development.</strong></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>We will share all information we collect from you, including the personal information with any third party if we in good faith believe it is required for the purposes of our compliance with any applicable law, regulation, legal process or enforceable governmental request/action or any manner required for the purposes of protecting our rights or interests.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>From time to time, we make the e-mail addresses of those who access our Website available to other reputable organizations whose products or services we think you might find interesting. If you do not want us to share your e-mail address with other companies or organizations, please let us know by emailing us at <strong><u>support@makairooms.com</u></strong>.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>Persons who supply us with their telephone numbers on-line may receive telephone or text message contact from us with information regarding new products and services or upcoming events. If you do not wish to receive such telephone calls or text messages, please let us know by e-mailing us at <strong><u>support@makairooms.com</u></strong>.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Ad Servers</u></strong><u>:</u> To try and bring you offers that are of interest to you, we have relationships with other companies that we allow to place ads on our Web pages. As a result of your visit to our Website, ad server companies may collect information such as your domain type, your IP address and clickstream information.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Non-Personally Identifiable Information (Non-PII)</u></strong><u>:</u> is information that cannot by itself be used to identify an individual person. Non-PII includes information received from the web browser, operating system, or device, including such things as information about the browser and browser settings, information about the operating system or device, the unique identifier assigned to a device, the web address of a web page visited, the name or type of mobile app, the time and date a web page or app was visited, the address of the referring web page, and other information about a web page or app. It could also include the number of times a particular browser or device has been shown a particular ad, or it may include generic categories about users and their interests (for example, &ldquo;Female PG Hunter&rdquo;). Non-PII also includes information about the precise geographic location of the device, which may be collected when the user of the device permits such collection.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Use of Non-PII</u></strong><u>:</u> In order to provide and improve our Services and to share relevant ads with you, provide interest-based advertising, show ads in a particular sequence, customize ads to a particular geographic region, determine when users respond to ads and reporting aggregated statistics regarding, for example, the effectiveness of online advertising campaigns we use and disclose to our advertising and analytics partners Non-PII that we collect, including cookie data, some log data, and mobile data. We also share anonymous profiles of users who view a property with RESPs and OSP web views.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Direct Contact with a RESP and OSP:</u></strong> If you fill out a form to contact a RESP (or use any other contact forms available on our Website) or call a RESP via our mobile site or app or Use contact info available on our website or app to contact we may share personally identifiable information that you share with us and information about your use of our Services with the party you wanted to contact. This may include data you input such as home, PG/Private Hostel, Religious Institution/ Dorm and Educational Institution / Hostel or any OSP search criteria or Log Data that we collect as you use the Services. Sometimes, if we are working with a third party to improve the leads we provide to our subscriber RESPs and OSP, we may provide that third party with additional but limited personally identifiable information for the sole purpose of their carrying out their duty to us.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>User-Generated Content</u></strong><u>:</u> If you use our user-generated content services, like posting a question, answer or blog on our Website, you should be aware that any personally identifiable information you submit there can be read, collected, or used by other users and could be used to send you unsolicited messages. We are not responsible for the personally identifiable information you choose to submit in these forums.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Protecting Ourselves and Our Users</u></strong><u>:</u> We may release personal information when we believe that doing so is appropriate to comply with a legitimate law, regulation, or legal request; to enforce or apply our policies; to initiate, render, bill, and collect for amounts owed to us; to protect our rights or property; to protect the safety of our users; to address fraud, security, or technical issues; or if we reasonably believe that an emergency involving immediate danger of death or serious physical injury to any person requires disclosure of communications or justifies disclosure of records without delay.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>All makairooms.com websites including this Website fully comply with all Indian Laws applicable. MAKAI ROOMS has always cooperated with all law enforcement inquires. MAKAI ROOMS may disclose all or part of your personal details in response to a request from the law enforcement authorities or in a case of a bona-fide requirement to prevent an imminent breach of the law.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Mobile Ad Networks and Analytics</u></strong><u>:</u> For our mobile products, we use third-party service providers for the limited purpose of helping us analyse your mobile Log Data and location data, so that we can improve and localize our Services, show you relevant advertisements, and study the way our mobile users interact with our Website and Services.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u><span style="font-size:19px;line-height:115%;">General Matters</span></u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>The Accuracy and Confidentiality of Your Account Information Is Your Responsibility: You are responsible for maintaining the secrecy and accuracy of your password, email address, and other account information at all times. We recommend a strong password that you do not use with other services. We are not responsible for personal data transmitted to a third party as a result of an incorrect email address.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Third-Party Websites</u></strong><u>:</u> Our Website may contain links to other websites. When you click on one of these links, you are navigating to another website. We do not accept liability for misuse of any information by any website controller to which we may link. We also do not have any responsibility of liability for the content on websites that use the makairooms.com search functionality. We encourage you to read the privacy statements of these websites, which may differ from ours.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Sale/Merger</u></strong><u>:</u> Information about our Users and our Website is a business asset of MAKAI ROOMS. Consequently, information about our Users, including personal information, will be disclosed as part of any merger or acquisition, creation of a separate business to provide the Website, our Services or fulfill products, sale or pledge of company assets as well as in the event of an insolvency, bankruptcy or receivership in which personal information would be transferred as one of the business assets of the company.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Security:</u></strong> We use commercially reasonable security measures to protect the loss, misuse, and alteration of the information under our control. However, we cannot absolutely guarantee the protection of any information shared with us.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><u>Policy Changes:</u></strong> We reserve the right to change, modify or update this Privacy Policy to reflect changes to our information practices, or any policy or guideline of the Website or Services, at any time and in our sole discretion. Any changes or modifications will be effective immediately upon posting of the revisions to the Website or Services. You waive any right you may have to receive specific notice of such changes or modifications. Your continued use of the Website or Services following the posting of changes or modifications will confirm your acceptance of such changes or modifications. If we make any change in how we use your personal information we will notify you by means of Change on this Website. We encourage you to periodically review this page for the latest information on our privacy practices</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                            </div>
                    <hr class="mt60">
                    <div class="mbp_pagination_tab">
                        <div class="row">
                            <div class="col-sm-6 col-lg-6">
                                <div class="pag_prev">
                                    <div class="detls">
                                        
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-lg-6">
                                <div class="pag_next text-right">
                                    <div class="detls">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
@section('extrajs')

@endsection